// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eCommerce.Backend.Data;

#nullable disable

namespace eCommerce.Backend.Migrations
{
    [DbContext(typeof(eCommerceContext))]
    [Migration("20220322142351_ChangeDataProductColorSize")]
    partial class ChangeDataProductColorSize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("eCommerce.Backend.Models.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("AppRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "customer"
                        });
                });

            modelBuilder.Entity("eCommerce.Backend.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AppUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Dob = new DateTime(1999, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@admin.com",
                            Name = "admin",
                            PasswordHash = "admin",
                            PhoneNumber = "0123456789",
                            RoleId = 1,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Dob = new DateTime(2000, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "customer@customer.com",
                            Name = "customer",
                            PasswordHash = "customer",
                            PhoneNumber = "0123456789",
                            RoleId = 2,
                            UserName = "customer"
                        });
                });

            modelBuilder.Entity("eCommerce.Backend.Models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2022, 3, 22, 21, 23, 50, 862, DateTimeKind.Local).AddTicks(7549));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("ID");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Áo",
                            Status = 0
                        },
                        new
                        {
                            ID = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Quần",
                            Status = 0
                        },
                        new
                        {
                            ID = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Khác",
                            Status = 0
                        },
                        new
                        {
                            ID = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Áo khoác",
                            ParentId = 1,
                            Status = 0
                        },
                        new
                        {
                            ID = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Áo dài tay",
                            ParentId = 1,
                            Status = 0
                        },
                        new
                        {
                            ID = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Áo Polo",
                            ParentId = 1,
                            Status = 0
                        },
                        new
                        {
                            ID = 7,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Áo T-Shirt",
                            ParentId = 1,
                            Status = 0
                        },
                        new
                        {
                            ID = 8,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Áo sơ mi",
                            ParentId = 1,
                            Status = 0
                        },
                        new
                        {
                            ID = 9,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Áo thể thao",
                            ParentId = 1,
                            Status = 0
                        },
                        new
                        {
                            ID = 10,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Áo in hình",
                            ParentId = 1,
                            Status = 0
                        },
                        new
                        {
                            ID = 11,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Quần sọt",
                            ParentId = 2,
                            Status = 0
                        },
                        new
                        {
                            ID = 12,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Quần dài",
                            ParentId = 2,
                            Status = 0
                        },
                        new
                        {
                            ID = 13,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Quần lót nam",
                            ParentId = 2,
                            Status = 0
                        },
                        new
                        {
                            ID = 14,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tất (vớ)",
                            ParentId = 3,
                            Status = 0
                        },
                        new
                        {
                            ID = 15,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Phụ kiện",
                            ParentId = 3,
                            Status = 0
                        });
                });

            modelBuilder.Entity("eCommerce.Backend.Models.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2022, 3, 22, 21, 23, 50, 862, DateTimeKind.Local).AddTicks(9193));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<decimal>("ShippingPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal>("TotalPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("eCommerce.Backend.Models.OrderDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductColorSizeID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("OrderID");

                    b.HasIndex("ProductColorSizeID");

                    b.ToTable("OrderDetails", (string)null);
                });

            modelBuilder.Entity("eCommerce.Backend.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<int>("CountRate")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2022, 3, 22, 21, 23, 50, 863, DateTimeKind.Local).AddTicks(3219));

                    b.Property<decimal>("DecreasedPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuantitySale")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalPointRate")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoryID = 4,
                            CountRate = 26,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DecreasedPrice = 399000m,
                            Name = "Áo khoác đa năng cản gió và chống UV",
                            Price = 499000m,
                            QuantitySale = 970,
                            Status = 0,
                            TotalPointRate = 128
                        },
                        new
                        {
                            ID = 2,
                            CategoryID = 7,
                            CountRate = 0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DecreasedPrice = 0m,
                            Name = "Áo thun nam Cotton Compact phiên bản Premium chống nhăn",
                            Price = 259000m,
                            QuantitySale = 0,
                            Status = 0,
                            TotalPointRate = 0
                        });
                });

            modelBuilder.Entity("eCommerce.Backend.Models.ProductColor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2022, 3, 22, 21, 23, 50, 863, DateTimeKind.Local).AddTicks(5368));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PathImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ProductID");

                    b.ToTable("ProductColors", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Đen",
                            PathImage = "https://mcdn2-coolmate.cdn.vccloud.vn/uploads/December2021/4-4_(1)_80x80.jpg",
                            ProductID = 1,
                            Status = 0
                        },
                        new
                        {
                            ID = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Xanh rêu",
                            PathImage = "https://mcdn2-coolmate.cdn.vccloud.vn/uploads/December2021/7-2_80x80.jpg",
                            ProductID = 1,
                            Status = 0
                        },
                        new
                        {
                            ID = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Đen",
                            PathImage = "https://mcdn2-coolmate.cdn.vccloud.vn/uploads/November2021/1-5avgg2cc_46_80x80.jpg",
                            ProductID = 2,
                            Status = 0
                        },
                        new
                        {
                            ID = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Trắng",
                            PathImage = "https://mcdn2-coolmate.cdn.vccloud.vn/uploads/November2021/3-7a_80x80.jpg",
                            ProductID = 2,
                            Status = 0
                        },
                        new
                        {
                            ID = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Xanh Navy",
                            PathImage = "https://mcdn2-coolmate.cdn.vccloud.vn/uploads/November2021/preimum_Tshirt_mau_xanh_navy_3_80x80.jpg",
                            ProductID = 2,
                            Status = 0
                        },
                        new
                        {
                            ID = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Xám",
                            PathImage = "https://mcdn2-coolmate.cdn.vccloud.vn/uploads/November2021/2-5a23_80x80.jpg",
                            ProductID = 2,
                            Status = 0
                        },
                        new
                        {
                            ID = 7,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Xám chì",
                            PathImage = "https://mcdn2-coolmate.cdn.vccloud.vn/uploads/November2021/1-4_(2)_80x80.jpg",
                            ProductID = 2,
                            Status = 0
                        },
                        new
                        {
                            ID = 8,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Xanh lam",
                            PathImage = "https://mcdn2-coolmate.cdn.vccloud.vn/uploads/November2021/6-1_(1)a_80x80.jpg",
                            ProductID = 2,
                            Status = 0
                        });
                });

            modelBuilder.Entity("eCommerce.Backend.Models.ProductColorImage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2022, 3, 22, 21, 23, 50, 863, DateTimeKind.Local).AddTicks(8121));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PathImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductColorID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ProductColorID");

                    b.ToTable("ProductColorImages", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "",
                            PathImage = "https://mcdn2-coolmate.cdn.vccloud.vn/uploads/December2021/den_tich_hop.jpg",
                            ProductColorID = 1,
                            Status = 0
                        },
                        new
                        {
                            ID = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "",
                            PathImage = "https://mcdn2-coolmate.cdn.vccloud.vn/uploads/December2021/anh_4_nen_.jpg",
                            ProductColorID = 1,
                            Status = 0
                        },
                        new
                        {
                            ID = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "",
                            PathImage = "https://mcdn2-coolmate.cdn.vccloud.vn/uploads/December2021/anh_2_nen.jpg",
                            ProductColorID = 1,
                            Status = 0
                        },
                        new
                        {
                            ID = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "",
                            PathImage = "https://mcdn2-coolmate.cdn.vccloud.vn/uploads/December2021/fix.jpg",
                            ProductColorID = 1,
                            Status = 0
                        },
                        new
                        {
                            ID = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "",
                            PathImage = "https://mcdn2-coolmate.cdn.vccloud.vn/uploads/December2021/anh_5_nen.jpg",
                            ProductColorID = 1,
                            Status = 0
                        },
                        new
                        {
                            ID = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "",
                            PathImage = "https://mcdn2-coolmate.cdn.vccloud.vn/uploads/December2021/anh_6_nen.jpg",
                            ProductColorID = 1,
                            Status = 0
                        },
                        new
                        {
                            ID = 7,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "",
                            PathImage = "https://mcdn2-coolmate.cdn.vccloud.vn/uploads/December2021/utich_hssop_FS-2.jpg",
                            ProductColorID = 2,
                            Status = 0
                        },
                        new
                        {
                            ID = 8,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "",
                            PathImage = "https://mcdn2-coolmate.cdn.vccloud.vn/uploads/December2021/2_87.jpg",
                            ProductColorID = 2,
                            Status = 0
                        },
                        new
                        {
                            ID = 9,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "",
                            PathImage = "https://mcdn2-coolmate.cdn.vccloud.vn/uploads/December2021/1_79.jpg",
                            ProductColorID = 2,
                            Status = 0
                        },
                        new
                        {
                            ID = 10,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "",
                            PathImage = "https://mcdn2-coolmate.cdn.vccloud.vn/uploads/December2021/face3_73.jpg",
                            ProductColorID = 2,
                            Status = 0
                        },
                        new
                        {
                            ID = 11,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "",
                            PathImage = "https://mcdn2-coolmate.cdn.vccloud.vn/uploads/December2021/4_6.jpg",
                            ProductColorID = 2,
                            Status = 0
                        },
                        new
                        {
                            ID = 12,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "",
                            PathImage = "https://mcdn2-coolmate.cdn.vccloud.vn/uploads/November2021/IMG_6130_91.jpg",
                            ProductColorID = 3,
                            Status = 0
                        },
                        new
                        {
                            ID = 13,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "",
                            PathImage = "https://mcdn2-coolmate.cdn.vccloud.vn/uploads/November2021/denn3-(2).jpg",
                            ProductColorID = 3,
                            Status = 0
                        },
                        new
                        {
                            ID = 14,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "",
                            PathImage = "https://mcdn2-coolmate.cdn.vccloud.vn/uploads/November2021/comb2_64.jpg",
                            ProductColorID = 3,
                            Status = 0
                        },
                        new
                        {
                            ID = 15,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "",
                            PathImage = "https://mcdn2-coolmate.cdn.vccloud.vn/uploads/November2021/MEM_MAI_(11)_(2).jpg",
                            ProductColorID = 3,
                            Status = 0
                        },
                        new
                        {
                            ID = 16,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "",
                            PathImage = "https://mcdn2-coolmate.cdn.vccloud.vn/uploads/November2021/1-5_39.jpg",
                            ProductColorID = 3,
                            Status = 0
                        },
                        new
                        {
                            ID = 17,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "",
                            PathImage = "https://mcdn2-coolmate.cdn.vccloud.vn/uploads/December2021/IMG_59801u.jpg",
                            ProductColorID = 4,
                            Status = 0
                        },
                        new
                        {
                            ID = 18,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "",
                            PathImage = "https://mcdn2-coolmate.cdn.vccloud.vn/uploads/December2021/1white.jpg",
                            ProductColorID = 4,
                            Status = 0
                        },
                        new
                        {
                            ID = 19,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "",
                            PathImage = "https://mcdn2-coolmate.cdn.vccloud.vn/uploads/November2021/IMG_6043.jpg",
                            ProductColorID = 4,
                            Status = 0
                        },
                        new
                        {
                            ID = 20,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "",
                            PathImage = "https://mcdn2-coolmate.cdn.vccloud.vn/uploads/November2021/IMG_6048.jpg",
                            ProductColorID = 4,
                            Status = 0
                        },
                        new
                        {
                            ID = 21,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "",
                            PathImage = "https://mcdn2-coolmate.cdn.vccloud.vn/uploads/November2021/3-111.jpg",
                            ProductColorID = 4,
                            Status = 0
                        },
                        new
                        {
                            ID = 22,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "",
                            PathImage = "https://mcdn2-coolmate.cdn.vccloud.vn/uploads/December2021/navy56_74-2_copy.jpg",
                            ProductColorID = 5,
                            Status = 0
                        },
                        new
                        {
                            ID = 23,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "",
                            PathImage = "https://mcdn2-coolmate.cdn.vccloud.vn/uploads/December2021/blue.jpg",
                            ProductColorID = 5,
                            Status = 0
                        },
                        new
                        {
                            ID = 24,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "",
                            PathImage = "https://mcdn2-coolmate.cdn.vccloud.vn/uploads/December2021/IMG_5855_74_copy.jpg",
                            ProductColorID = 5,
                            Status = 0
                        },
                        new
                        {
                            ID = 25,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "",
                            PathImage = "https://mcdn2-coolmate.cdn.vccloud.vn/uploads/December2021/IMG_5878_copy.jpg",
                            ProductColorID = 5,
                            Status = 0
                        },
                        new
                        {
                            ID = 26,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "",
                            PathImage = "https://mcdn2-coolmate.cdn.vccloud.vn/uploads/November2021/xamkso_13.jpg",
                            ProductColorID = 6,
                            Status = 0
                        },
                        new
                        {
                            ID = 27,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "",
                            PathImage = "https://mcdn2-coolmate.cdn.vccloud.vn/uploads/December2021/1grey.jpg",
                            ProductColorID = 6,
                            Status = 0
                        },
                        new
                        {
                            ID = 28,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "",
                            PathImage = "https://mcdn2-coolmate.cdn.vccloud.vn/uploads/November2021/IMG_6248.jpg",
                            ProductColorID = 6,
                            Status = 0
                        },
                        new
                        {
                            ID = 29,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "",
                            PathImage = "https://mcdn2-coolmate.cdn.vccloud.vn/uploads/November2021/IMG_6269.jpg",
                            ProductColorID = 6,
                            Status = 0
                        },
                        new
                        {
                            ID = 30,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "",
                            PathImage = "https://mcdn2-coolmate.cdn.vccloud.vn/uploads/November2021/IMG_6288.jpg",
                            ProductColorID = 6,
                            Status = 0
                        },
                        new
                        {
                            ID = 31,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "",
                            PathImage = "https://mcdn2-coolmate.cdn.vccloud.vn/uploads/November2021/2-1_(3)_(1).jpg",
                            ProductColorID = 6,
                            Status = 0
                        },
                        new
                        {
                            ID = 32,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "",
                            PathImage = "https://mcdn2-coolmate.cdn.vccloud.vn/uploads/December2021/acompax7.jpg",
                            ProductColorID = 7,
                            Status = 0
                        },
                        new
                        {
                            ID = 33,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "",
                            PathImage = "https://mcdn2-coolmate.cdn.vccloud.vn/uploads/December2021/penc.jpg",
                            ProductColorID = 7,
                            Status = 0
                        },
                        new
                        {
                            ID = 34,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "",
                            PathImage = "https://mcdn2-coolmate.cdn.vccloud.vn/uploads/November2021/compc2_13.jpg",
                            ProductColorID = 7,
                            Status = 0
                        },
                        new
                        {
                            ID = 35,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "",
                            PathImage = "https://mcdn2-coolmate.cdn.vccloud.vn/uploads/November2021/compax1.jpg",
                            ProductColorID = 8,
                            Status = 0
                        },
                        new
                        {
                            ID = 36,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "",
                            PathImage = "https://mcdn2-coolmate.cdn.vccloud.vn/uploads/December2021/bluelam.jpg",
                            ProductColorID = 8,
                            Status = 0
                        },
                        new
                        {
                            ID = 37,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "",
                            PathImage = "https://mcdn2-coolmate.cdn.vccloud.vn/uploads/December2021/DAI04411u.jpg",
                            ProductColorID = 8,
                            Status = 0
                        },
                        new
                        {
                            ID = 38,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "",
                            PathImage = "https://mcdn2-coolmate.cdn.vccloud.vn/uploads/November2021/DAI04428_(1).jpg",
                            ProductColorID = 8,
                            Status = 0
                        },
                        new
                        {
                            ID = 39,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "",
                            PathImage = "https://mcdn2-coolmate.cdn.vccloud.vn/uploads/November2021/6-0_(5)_(1)_86.jpg",
                            ProductColorID = 8,
                            Status = 0
                        },
                        new
                        {
                            ID = 40,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "",
                            PathImage = "https://mcdn2-coolmate.cdn.vccloud.vn/uploads/November2021/6-2_(2).jpg",
                            ProductColorID = 8,
                            Status = 0
                        });
                });

            modelBuilder.Entity("eCommerce.Backend.Models.ProductColorSize", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2022, 3, 22, 21, 23, 50, 863, DateTimeKind.Local).AddTicks(6759));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ProductColorID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ProductColorID");

                    b.ToTable("ProductColorSizes", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "M",
                            ProductColorID = 1,
                            Quantity = 0,
                            Status = 0
                        },
                        new
                        {
                            ID = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "L",
                            ProductColorID = 1,
                            Quantity = 0,
                            Status = 0
                        },
                        new
                        {
                            ID = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "XL",
                            ProductColorID = 1,
                            Quantity = 100,
                            Status = 0
                        },
                        new
                        {
                            ID = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "2XL",
                            ProductColorID = 1,
                            Quantity = 20,
                            Status = 0
                        },
                        new
                        {
                            ID = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "M",
                            ProductColorID = 2,
                            Quantity = 2,
                            Status = 0
                        },
                        new
                        {
                            ID = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "L",
                            ProductColorID = 2,
                            Quantity = 0,
                            Status = 0
                        },
                        new
                        {
                            ID = 7,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "XL",
                            ProductColorID = 2,
                            Quantity = 1,
                            Status = 0
                        },
                        new
                        {
                            ID = 8,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "2XL",
                            ProductColorID = 2,
                            Quantity = 0,
                            Status = 0
                        },
                        new
                        {
                            ID = 9,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "S",
                            ProductColorID = 3,
                            Quantity = 2,
                            Status = 0
                        },
                        new
                        {
                            ID = 10,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "M",
                            ProductColorID = 3,
                            Quantity = 0,
                            Status = 0
                        },
                        new
                        {
                            ID = 11,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "L",
                            ProductColorID = 3,
                            Quantity = 0,
                            Status = 0
                        },
                        new
                        {
                            ID = 12,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "XL",
                            ProductColorID = 3,
                            Quantity = 100,
                            Status = 0
                        },
                        new
                        {
                            ID = 13,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "2XL",
                            ProductColorID = 3,
                            Quantity = 20,
                            Status = 0
                        },
                        new
                        {
                            ID = 14,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "S",
                            ProductColorID = 4,
                            Quantity = 2,
                            Status = 0
                        },
                        new
                        {
                            ID = 15,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "M",
                            ProductColorID = 4,
                            Quantity = 2,
                            Status = 0
                        },
                        new
                        {
                            ID = 16,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "L",
                            ProductColorID = 4,
                            Quantity = 0,
                            Status = 0
                        },
                        new
                        {
                            ID = 17,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "XL",
                            ProductColorID = 4,
                            Quantity = 1,
                            Status = 0
                        },
                        new
                        {
                            ID = 18,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "2XL",
                            ProductColorID = 4,
                            Quantity = 0,
                            Status = 0
                        },
                        new
                        {
                            ID = 19,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "S",
                            ProductColorID = 5,
                            Quantity = 2,
                            Status = 0
                        },
                        new
                        {
                            ID = 20,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "M",
                            ProductColorID = 5,
                            Quantity = 2,
                            Status = 0
                        },
                        new
                        {
                            ID = 21,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "L",
                            ProductColorID = 5,
                            Quantity = 0,
                            Status = 0
                        },
                        new
                        {
                            ID = 22,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "XL",
                            ProductColorID = 5,
                            Quantity = 1,
                            Status = 0
                        },
                        new
                        {
                            ID = 23,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "2XL",
                            ProductColorID = 5,
                            Quantity = 0,
                            Status = 0
                        },
                        new
                        {
                            ID = 24,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "S",
                            ProductColorID = 6,
                            Quantity = 2,
                            Status = 0
                        },
                        new
                        {
                            ID = 25,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "M",
                            ProductColorID = 6,
                            Quantity = 2,
                            Status = 0
                        },
                        new
                        {
                            ID = 26,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "L",
                            ProductColorID = 6,
                            Quantity = 0,
                            Status = 0
                        },
                        new
                        {
                            ID = 27,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "XL",
                            ProductColorID = 6,
                            Quantity = 1,
                            Status = 0
                        },
                        new
                        {
                            ID = 28,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "2XL",
                            ProductColorID = 6,
                            Quantity = 0,
                            Status = 0
                        },
                        new
                        {
                            ID = 29,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "S",
                            ProductColorID = 7,
                            Quantity = 2,
                            Status = 0
                        },
                        new
                        {
                            ID = 30,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "M",
                            ProductColorID = 7,
                            Quantity = 2,
                            Status = 0
                        },
                        new
                        {
                            ID = 31,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "L",
                            ProductColorID = 7,
                            Quantity = 0,
                            Status = 0
                        },
                        new
                        {
                            ID = 32,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "XL",
                            ProductColorID = 7,
                            Quantity = 1,
                            Status = 0
                        },
                        new
                        {
                            ID = 33,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "2XL",
                            ProductColorID = 7,
                            Quantity = 0,
                            Status = 0
                        },
                        new
                        {
                            ID = 34,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "M",
                            ProductColorID = 8,
                            Quantity = 0,
                            Status = 0
                        },
                        new
                        {
                            ID = 35,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "M",
                            ProductColorID = 8,
                            Quantity = 0,
                            Status = 0
                        },
                        new
                        {
                            ID = 36,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "L",
                            ProductColorID = 8,
                            Quantity = 0,
                            Status = 0
                        },
                        new
                        {
                            ID = 37,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "XL",
                            ProductColorID = 8,
                            Quantity = 0,
                            Status = 0
                        },
                        new
                        {
                            ID = 38,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "2XL",
                            ProductColorID = 8,
                            Quantity = 0,
                            Status = 0
                        });
                });

            modelBuilder.Entity("eCommerce.Backend.Models.Rate", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2022, 3, 22, 21, 23, 50, 863, DateTimeKind.Local).AddTicks(8962));

                    b.Property<int>("Point")
                        .HasMaxLength(200)
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ProductID");

                    b.HasIndex("UserID");

                    b.ToTable("Rates", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Content = "Good",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Point = 5,
                            ProductID = 1,
                            Status = 1,
                            UserID = 1
                        },
                        new
                        {
                            ID = 2,
                            Content = "Bad",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Point = 1,
                            ProductID = 1,
                            Status = 1,
                            UserID = 1
                        },
                        new
                        {
                            ID = 3,
                            Content = "Good",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Point = 3,
                            ProductID = 1,
                            Status = 0,
                            UserID = 2
                        },
                        new
                        {
                            ID = 4,
                            Content = "Good",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Point = 4,
                            ProductID = 1,
                            Status = 3,
                            UserID = 2
                        });
                });

            modelBuilder.Entity("eCommerce.Backend.Models.Slide", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2022, 3, 22, 21, 23, 50, 864, DateTimeKind.Local).AddTicks(2269));

                    b.Property<string>("LinkProduct")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PathImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("ID");

                    b.ToTable("Slides", (string)null);
                });

            modelBuilder.Entity("eCommerce.Backend.Models.AppUser", b =>
                {
                    b.HasOne("eCommerce.Backend.Models.AppRole", "AppRole")
                        .WithMany("AppUsers")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppRole");
                });

            modelBuilder.Entity("eCommerce.Backend.Models.Order", b =>
                {
                    b.HasOne("eCommerce.Backend.Models.AppUser", "AppUser")
                        .WithMany("Orders")
                        .HasForeignKey("UserID");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("eCommerce.Backend.Models.OrderDetail", b =>
                {
                    b.HasOne("eCommerce.Backend.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eCommerce.Backend.Models.ProductColorSize", "ProductColorSize")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductColorSizeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("ProductColorSize");
                });

            modelBuilder.Entity("eCommerce.Backend.Models.Product", b =>
                {
                    b.HasOne("eCommerce.Backend.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("eCommerce.Backend.Models.ProductColor", b =>
                {
                    b.HasOne("eCommerce.Backend.Models.Product", "Product")
                        .WithMany("ProductColors")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("eCommerce.Backend.Models.ProductColorImage", b =>
                {
                    b.HasOne("eCommerce.Backend.Models.ProductColor", "ProductColor")
                        .WithMany("ProductColorImages")
                        .HasForeignKey("ProductColorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductColor");
                });

            modelBuilder.Entity("eCommerce.Backend.Models.ProductColorSize", b =>
                {
                    b.HasOne("eCommerce.Backend.Models.ProductColor", "ProductColor")
                        .WithMany("ProductColorSizes")
                        .HasForeignKey("ProductColorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductColor");
                });

            modelBuilder.Entity("eCommerce.Backend.Models.Rate", b =>
                {
                    b.HasOne("eCommerce.Backend.Models.Product", "Product")
                        .WithMany("Rates")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eCommerce.Backend.Models.AppUser", "AppUser")
                        .WithMany("Rates")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("eCommerce.Backend.Models.AppRole", b =>
                {
                    b.Navigation("AppUsers");
                });

            modelBuilder.Entity("eCommerce.Backend.Models.AppUser", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Rates");
                });

            modelBuilder.Entity("eCommerce.Backend.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("eCommerce.Backend.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("eCommerce.Backend.Models.Product", b =>
                {
                    b.Navigation("ProductColors");

                    b.Navigation("Rates");
                });

            modelBuilder.Entity("eCommerce.Backend.Models.ProductColor", b =>
                {
                    b.Navigation("ProductColorImages");

                    b.Navigation("ProductColorSizes");
                });

            modelBuilder.Entity("eCommerce.Backend.Models.ProductColorSize", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
